### ISSUE TITLE
[1.8][EnchantingPlus-1.8-3.1.0a1.jar] Crashed in the GUI

### ISSUE THREAD

**Issue by Kris1432** [Epoxide-Software/EnchantingPlus#103]
I just opened up table and got this crash [Forge 1555]

http://pastebin.com/GNiGW1J6

**Comment by Darkhax** [comment]
It seems like this issue is related to the lack of a null check in the Tool Tip code. The Enchanting Plus mod is currently being rewritten from the ground up, and once we are confident with our 1.7.10 release, a 1.8 release is likely to follow. We have also moved to a new repository, which can be found [here](https://github.com/Epoxide-MC/Enchanting-Plus). Due to all of our changes, this report is not valid, however will ensure that this issue does not exist in V4 of the mod.
