### ISSUE TITLE
[Mod Interaction] Infinite XP

### ISSUE THREAD

**Issue by VT-14** [Epoxide-Software/EnchantingPlus#104]
The Advanced Enchantment Table returns levels rather than experience.  As this is similar to how the vanilla enchanting mechanic, I'm not sure if it can be reasonably changed.

However, this means that by using a mod that allows you to store your experience (namely Open Blocks, but there are more), you can dump your excess experience, enchant something using an exact number of levels, pick up all your experience, and disenchant it to gain back some number of levels on top of your current level and end up with more levels than you started with.

For example, say you have 30 experience levels (1395 xp).  You store experience until you are level 10 (keep 160 xp; store 1235, which is enough for 28 levels from 0).  Use all 10 of your levels to make something, then pick up all your experience (28 levels worth), and disenchant that item for 10 levels to bring you up to level 38 (2543 xp).  1148 xp has been created, enough to go from level 0 to 27.

**Comment by Darkhax** [comment]
Thank you for reporting this issue. I am having some trouble trying to figure out what you exactly mean. In this exploit, are you activating the exp storage at the same time you are interacting with the table? IE standing on an EXP drain, and then opening the enchantment table gui?

**Comment by VT-14** [comment]
They can be as far away as wanted.  I think the issue is with most experience storage systems using xp and the Advanced Enchantment Table using Levels.

Adding 10 levels when you are level 0 will add 160 xp points.
Adding 10 levels when you are already level 10 will add 390 xp points.
Adding 10 levels when you are already level 30 will add 1525 xp points.

To answer your question directly: I did this with the xp tank in the same room, but I was not standing on the drain, nor was I doing something to add xp to myself while in the GUI.

Also, probably relevant:
Minecraft 1.7.10
Forge 10.13.4.1541
EnchantingPlus 3.0.2-d
Open Blocks 1.4.4

**Comment by Darkhax** [comment]
This makes much more sense now. The issue comes with levels being worth different amounts at different levels. This is certainly an issue, and we will solve this before we release E+ 4.

**Comment by Darkhax** [comment]
We are currently in a transition from Enchanting plus 3 and Enchanting plus 4. Enchanting plus 3 is the current version available for download, and Enchanting plus 4 is the complete rewrite that is being done. For Enchanting plus 4, we are using a new Github page to help keep things organised. This issue exists in both versions of the mod, so I have created an issue on the new page which documents this issue a bit further. Because version 3 of Enchanting plus is discontinued, I will be closing this version of the issue, however you can follow the status of this issue on the [other GitHub page](https://github.com/Epoxide-MC/Enchanting-Plus/issues/4). Thank you again for reporting this to us.
